# Site settings
title: from-diff0
description: A Jekyll site built for GitHub Pages with Bootstrap
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# GitHub Pages compatibility
github: [metadata]

# Collections
collections:
  notes:
    output: true
    permalink: /notes/:name/
    sort_by: date

# Defaults
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md